apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orders-project1-staging-catalog-service
spec:
  gateways:
  - orders-project1-staging-gateway
  hosts:
  - catalog-service.orders-project1-staging.40.87.6.40.xip.io
  http:
  - route:
    - destination:
        host: catalog-service.orders-project1-staging.svc.cluster.local
        subset: blue
      weight: 0
    - destination:
        host: catalog-service.orders-project1-staging.svc.cluster.local
        subset: green
      weight: 100
