apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: orders-project1-production-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"